server:
#  ssl:
#    enabled: true
#    key-store-password: password
#    key-store-type: pkcs12
#    key-store: classpath:glc.jks
#    key-password: password
#    key-alias: glc
  port: 8081
spring:
  application:
    name: glc-cecurity
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/greenlc-security
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/eazybankdev/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
       defaultZone: http://glc:glc@localhost:8761/eureka, http://glc:glc@peer-1-server.com:9001/eureka, http://glc:glc@peer-2-server.com:9002/eureka, http://glc:glc@peer-3-server.com:9003/eureka
marjan:
  glc:
    jwtExpirationMs: '19000000'
    jwtRefreshExpirationMs: '86400000'
    jwtSecret: marjanSecretKey
