spring:
  application:
    name: glc-discovery-service
    
---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: default
server:
  port: 8761  
eureka:
  instance:
    hostname: localhost
  client:
    region: Dhaka
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://glc:glc@${eureka.instance.hostname}:${server.port}/eureka/    

---
spring:
  profiles: peer-1
  application:
    name: glc-discovery-cluster
server:
  port: 9001  
eureka:
  server:
    peer-node-read-timeout-ms: 5000
    eviction-interval-timer-in-ms: 10000
    renewal-percent-threshold: 0.95
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: true
  instance:
    hostname: peer-1-server.com    
  client:
    region: default
    registerWithEureka: true
    fetchRegistry: true 
    registryFetchIntervalSeconds: 5      
    serviceUrl:
      defaultZone: http://glc:glc@peer-2-server.com:9002/eureka/,http://glc:glc@peer-3-server.com:9003/eureka/
 
---
spring:
  profiles: peer-2
  application:
    name: glc-discovery-cluster
server:
  port: 9002
eureka:
  server:
    peer-node-read-timeout-ms: 5000
    eviction-interval-timer-in-ms: 10000
    renewal-percent-threshold: 0.95
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: true

  instance:
    hostname: peer-2-server.com      
  client:
    region: default
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5       
    serviceUrl:
      defaultZone: http://glc:glc@peer-1-server.com:9001/eureka/,http://glc:glc@peer-3-server.com:9003/eureka/
 
---
spring:
  profiles: peer-3
  application:
    name: glc-discovery-cluster
server:
  port: 9003
eureka:
  server:
    peer-node-read-timeout-ms: 5000
    eviction-interval-timer-in-ms: 10000
    renewal-percent-threshold: 0.95
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: true
  instance:
    hostname: peer-3-server.com    
  client:
    region: default
    registerWithEureka: true
    fetchRegistry: true 
    registryFetchIntervalSeconds: 5  
    serviceUrl:
      defaultZone: http://glc:glc@peer-1-server.com:9001/eureka/,http://glc:glc@peer-2-server.com:9002/eureka/
